In [2]:
import pandas as pd
import os
os.chdir("/Users/adrianamedrano/Documents/Ariana/Residencias/PrototipoResidencias/DataSets_Codigo")
df_clied = pd.read_csv('Mer_clied.txt', encoding='latin1')
df_clifd = pd.read_csv('Mer_Clifd.txt', encoding="latin1")
df_clird = pd.read_csv('Mer_Clird.txt', encoding='latin1')
df_clifad = pd.read_csv('Mer_Clifad.txt', encoding='latin1')
df_clind = pd.read_csv('Mer_Clind.txt', encoding='latin1')
df_articulos = pd.read_csv('Articulos.txt', encoding='latin1')
df_clied.rename(columns={'Fecncre': 'Fec'}, inplace=True)
df_clifd.rename(columns={'Fecfac': 'Fec'}, inplace=True)
df_clird.rename(columns={'Fecrem': 'Fec'}, inplace=True)
df_clifad.rename(columns={'Fecfac': 'Fec'}, inplace=True)
df_resultado = pd.concat([df_clied[['Claart', 'Cant', 'Fec']],
                          df_clifd[['Claart', 'Cant', 'Fec']],
                          df_clird[['Claart', 'Cant', 'Fec']],
                          df_clifad[['Claart', 'Cant', 'Fec']]])
df_resultado.reset_index(drop=True, inplace=True)
numeros_factura = df_clifd['Numfac'].unique()
if len(numeros_factura) < len(df_resultado):
    numeros_factura = list(numeros_factura) * (len(df_resultado) // len(numeros_factura)) + list(numeros_factura)[:len(df_resultado) % len(numeros_factura)]
df_resultado['Numfac'] = numeros_factura[:len(df_resultado)]
df_resultado = pd.merge(df_resultado, df_articulos[['Claart','Desart']], on='Claart', how='left')
df_resultado

             Claart   Cant       Fec    Numfac                     Desart
0       04HBISPR100    8.0  31/08/20  ZI030471            Bisagra 1 p rem
1           0614687    1.0  31/08/20  ZI030430       Atomizador de 1/2lto
2           06GAR20    4.0  31/08/20  ZI030435             Garrafa 20 Lts
3           0624069    1.0  31/08/20  ZI030436  Taladro Inalambrico 24069
4         04HPPB141  100.0  31/08/20  ZI030439        Pijas p/broca 1/4x1
...             ...    ...       ...       ...                        ...
423002     01CEMBIG    2.0  27/02/24  ZI031652  Cemento big bag cruz azul
423003      01VAR38   25.0  27/02/24  ZI031653     Varilla corr 3/8 x 12m
423004      01ALREC   30.0  27/02/24  ZI031656           Alambre recocido
423005    01EST1520    5.0  27/02/24  ZI031657       Estribo 15x20(10x15)
423006        01CAL   10.0  27/02/24  ZI031658               Calidra 25kg

[423007 rows x 5 columns]

In [3]:
import pandas as pd
import os
os.chdir("/Users/adrianamedrano/Documents/Ariana/Residencias/PrototipoResidencias/DataSets_Codigo")
df_clind = pd.read_csv('Mer_Clind.txt', encoding='latin1')
#print(df_clind)
df_merged = pd.merge(df_resultado, df_clind[['Numfac']], on='Numfac', how='left', indicator=True)
df_merged = df_merged[df_merged['_merge'] == 'left_only']
df_merged.drop(columns=['_merge'], inplace=True)
df_merged = df_merged.copy()
df_merged.drop(columns=['Numfac'], inplace=True)
df_merged

             Claart   Cant       Fec                     Desart
0       04HBISPR100    8.0  31/08/20            Bisagra 1 p rem
1           0614687    1.0  31/08/20       Atomizador de 1/2lto
2           06GAR20    4.0  31/08/20             Garrafa 20 Lts
3           0624069    1.0  31/08/20  Taladro Inalambrico 24069
4         04HPPB141  100.0  31/08/20        Pijas p/broca 1/4x1
...             ...    ...       ...                        ...
433321     01CEMBIG    2.0  27/02/24  Cemento big bag cruz azul
433322      01VAR38   25.0  27/02/24     Varilla corr 3/8 x 12m
433323      01ALREC   30.0  27/02/24           Alambre recocido
433324    01EST1520    5.0  27/02/24       Estribo 15x20(10x15)
433325        01CAL   10.0  27/02/24               Calidra 25kg

[412534 rows x 4 columns]

In [4]:
import pandas as pd
import os
os.chdir("/Users/adrianamedrano/Documents/Ariana/Residencias/PrototipoResidencias/DataSets_Codigo")
df_articulos = pd.read_csv('Articulos.txt', encoding='latin1')
df_merged['Fec'] = pd.to_datetime(df_merged['Fec'])
df_merged['AÃ±o'] = df_merged['Fec'].dt.year
clave_articulo = input("Por favor, ingrese la clave del artÃ­culo que desea filtrar: ")
df_filtrado = df_merged[(df_merged['Claart'] == clave_articulo) & (df_merged['AÃ±o'] >= 2017)]
df_ventas_por_fecha = df_filtrado.groupby(['Claart', 'Fec'])['Cant'].sum().reset_index()
df_ventas = pd.merge(df_ventas_por_fecha, df_articulos[['Claart', 'Desart']], on='Claart', how='left')
df_ventas = df_ventas[['Claart', 'Desart', 'Cant', 'Fec']]
df_ventas['Fec'] = pd.to_datetime(df_ventas['Fec'], errors='coerce')
df_ventas["Fec"] = df_ventas["Fec"].dt.strftime("%d/%m/%y")
print("Ventas por fecha para la clave del artÃ­culo:", clave_articulo)
df_ventas

Ventas por fecha para la clave del artÃ­culo: 06ALPN34

       Claart                      Desart  Cant       Fec
0    06ALPN34  Alambre puas 34 kg Novillo  60.0  24/07/18
1    06ALPN34  Alambre puas 34 kg Novillo  12.0  01/08/18
2    06ALPN34  Alambre puas 34 kg Novillo   4.0  30/08/18
3    06ALPN34  Alambre puas 34 kg Novillo   2.0  31/08/18
4    06ALPN34  Alambre puas 34 kg Novillo   1.0  07/09/18
..        ...                         ...   ...       ...
140  06ALPN34  Alambre puas 34 kg Novillo   2.0  15/02/24
141  06ALPN34  Alambre puas 34 kg Novillo   9.0  16/02/24
142  06ALPN34  Alambre puas 34 kg Novillo   3.0  19/02/24
143  06ALPN34  Alambre puas 34 kg Novillo   3.0  22/02/24
144  06ALPN34  Alambre puas 34 kg Novillo   2.0  27/02/24

[145 rows x 4 columns]

In [5]:
df_ventas.to_csv('/Users/adrianamedrano/Documents/Ariana/Residencias/PrototipoResidencias/DataSets_Codigo/Mer_Filtrado.txt', index=False, encoding="latin1")

In [6]:
import pandas as pd
df_filtrado = pd.read_csv('Mer_Filtrado.txt', encoding="latin1")
df_filtrado['Fec'] = pd.to_datetime(df_filtrado['Fec'])
df_filtrado = df_filtrado[df_filtrado['Fec'].dt.year != 2024]
df_filtrado.to_csv('Mer_Filtrado_sin_2024.txt', index=False)
df_filtrado['Fec'] = pd.to_datetime(df_filtrado['Fec'], errors='coerce')
df_filtrado["Fec"] = df_filtrado["Fec"].dt.strftime("%d/%m/%y")
df_filtrado

       Claart                      Desart  Cant       Fec
0    06ALPN34  Alambre puas 34 kg Novillo  60.0  24/07/18
1    06ALPN34  Alambre puas 34 kg Novillo  12.0  08/01/18
2    06ALPN34  Alambre puas 34 kg Novillo   4.0  30/08/18
3    06ALPN34  Alambre puas 34 kg Novillo   2.0  31/08/18
4    06ALPN34  Alambre puas 34 kg Novillo   1.0  09/07/18
..        ...                         ...   ...       ...
126  06ALPN34  Alambre puas 34 kg Novillo   1.0  27/11/23
127  06ALPN34  Alambre puas 34 kg Novillo   4.0  12/01/23
128  06ALPN34  Alambre puas 34 kg Novillo   1.0  12/02/23
129  06ALPN34  Alambre puas 34 kg Novillo  13.0  14/12/23
130  06ALPN34  Alambre puas 34 kg Novillo   2.0  27/12/23

[131 rows x 4 columns]

In [12]:
#EJECUTAR EN DEPNOTE
import os
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import TimeSeriesSplit
import warnings
warnings.filterwarnings('ignore', category=pd.core.common.SettingWithCopyWarning)
warnings.filterwarnings('ignore', category=UserWarning)
os.chdir(r'/work/DataSets_Codigo')
df_filtrado = pd.read_csv('Mer_Filtrado_sin_2024.txt', encoding="latin1")
df_filtrado['Fec'] = pd.to_datetime(df_filtrado['Fec'])
df_filtrado['Mes'] = df_filtrado['Fec'].dt.month
df_filtrado['AÃ±o'] = df_filtrado['Fec'].dt.year
df_filtrado['Trimestre'] = df_filtrado['Fec'].dt.quarter
df_filtrado['DiaSemana'] = df_filtrado['Fec'].dt.weekday
df_filtrado['FinDeSemana'] = (df_filtrado['DiaSemana'] >= 5).astype(int)
ventas_mensuales = df_filtrado.groupby(['AÃ±o', 'Mes'])['Cant'].sum().reset_index()
ventas_mensuales_agregadas = df_filtrado.groupby(['Mes']).agg({'Cant': 'sum'}).reset_index()
ventas_mensuales_agregadas.rename(columns={'Cant': 'Ventas_Hist'}, inplace=True)
ventas_mensuales['Ventas_Movil'] = ventas_mensuales['Cant'].rolling(window=3, min_periods=1).mean()
Q1 = ventas_mensuales.quantile(0.25)
Q3 = ventas_mensuales.quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = (ventas_mensuales < lower_bound) | (ventas_mensuales > upper_bound)
ventas_mensuales_filt = ventas_mensuales[~outliers.any(axis=1)]
tscv = TimeSeriesSplit(n_splits=5)
best_params_xgb = {'n_estimators': 300, 'max_depth': 10}
def add_product_sales_history_features(df, history_months=[1, 3, 6]):
    for month in history_months:
        df[f'Sales_Last_{month}_Months'] = df['Cant'].shift().rolling(window=month).sum().fillna(0)
    return df
ventas_mensuales_filt = add_product_sales_history_features(ventas_mensuales_filt)
predicciones_2024_xgb = []
for mes in range(1, 13):
    df_mes = ventas_mensuales_filt[ventas_mensuales_filt['Mes'] == mes]
    if not df_mes.empty:
        X = df_mes[['AÃ±o', 'Ventas_Movil', 'Sales_Last_1_Months', 'Sales_Last_3_Months', 'Sales_Last_6_Months']].copy()  
        y = df_mes['Cant']
        xgb_model = xgb.XGBRegressor(**best_params_xgb, random_state=42)
        xgb_model.fit(X, y)
        ventas_movil_mes = df_mes['Ventas_Movil'].values[0]
        ventas_pred_xgb = xgb_model.predict([[2024, ventas_movil_mes] + list(df_mes.iloc[-1, -3:])])
        ventas_pred_enteras_xgb = int(round(ventas_pred_xgb[0]))
        predicciones_2024_xgb.append({'AÃ±o': 2024, 'Mes': mes, 'Ventas': ventas_pred_enteras_xgb})
    else:
        print(f"No hay datos disponibles para el mes {mes}")
predicciones_2024_xgb = pd.DataFrame(predicciones_2024_xgb)
print(predicciones_2024_xgb)

ModuleNotFoundError: No module named 'xgboost'

In [14]:
import pandas as pd
import os
os.chdir("/Users/adrianamedrano/Documents/Ariana/Residencias/PrototipoResidencias/DataSets_Codigo")
df_filtrado = pd.read_csv('Mer_Filtrado.txt', encoding="latin1")
df_filtrado['Fec'] = pd.to_datetime(df_filtrado['Fec'], format='%d/%m/%y', errors='coerce')
ventas_2024 = df_filtrado[df_filtrado['Fec'].dt.year == 2024]
ventas_mensuales = ventas_2024.groupby(ventas_2024['Fec'].dt.to_period('M')).sum().reset_index()
ventas_mensuales['Mes'] = ventas_mensuales['Fec'].dt.month
print(ventas_mensuales)

       Fec  Cant  Mes
0  2024-01   7.0    1
1  2024-02  31.0    2

/var/folders/cn/s8xbm9k519n2w4bqvq70nvmr0000gn/T/ipykernel_2517/309575035.py:7: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  ventas_mensuales = ventas_2024.groupby(ventas_2024['Fec'].dt.to_period('M')).sum().reset_index()

In [ ]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
plt.figure(figsize=[10, 6])
plt.plot(ventas_mensuales['Mes'], ventas_mensuales['Cant'], marker='o', label='Ventas Reales')
#plt.plot(predicciones_2024['Mes'], predicciones_2024['Ventas'], marker='o', label='Ventas Predichas')
plt.plot(predicciones_2024_xgb['Mes'], predicciones_2024_xgb['Ventas'], marker='o', label='Ventas Predichas')
plt.title('ComparaciÃ³n de Ventas Reales y Predichas para 2023')
plt.xlabel('Mes')
plt.ylabel('Total de ventas')
plt.legend()
plt.grid(True)
plt.xticks(np.arange(1, 13))
plt.show()